version: '3.8'

services:
  backend:
    stdin_open: true
    tty: true
    build: ./services/backend
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
  dev:
    stdin_open: true
    tty: true
    build: 
      context: ./services/backend
      dockerfile: Dockerfile_dev
    ports:
      - 5000:5000
      - 5678:5678
    volumes:
      - ./services/backend:/app
    profiles:
      - dev